### PR TITLE
Added my pic

### PR DESCRIPTION
**Pull request by dmitrykrivaltsevich**
My pic

### CODE REVIEW

**Comment by AntonZarutsky** [comment]
AAAAAAAAAA

**Comment by AntonZarutsky** [comment]
let's make your PR more popular

**Comment by AntonZarutsky** [comment]
by

**Comment by AntonZarutsky** [comment]
adding

**Comment by AntonZarutsky** [comment]
some

**Comment by AntonZarutsky** [comment]
amounts

**Comment by AntonZarutsky** [comment]
of

**Comment by AntonZarutsky** [comment]
comments

**Comment by AntonZarutsky** [comment]
---

**Comment by AntonZarutsky** [comment]
Now

**Comment by AntonZarutsky** [comment]
you

**Comment by AntonZarutsky** [comment]
have

wow

**Comment by AntonZarutsky** [comment]
more

**Comment by AntonZarutsky** [comment]
comments

NOPE

**Comment by AntonZarutsky** [comment]
than

**Comment by AntonZarutsky** [comment]
others

**Comment by AntonZarutsky** [comment]
---

**Comment by AntonZarutsky** [comment]
Please, add your comments, instead of modifying my ones

**Comment by AntonZarutsky** [comment]
Lust auf ein kaffee?

**Comment by AntonZarutsky** [comment]
@dmitrykrivaltsevich  ping...

**Comment by AntonZarutsky** [comment]
London, Capital of Great Britain  
London is the capital of Great Britain, its political, economic, and commercial centre. It is one of the largest cities in the world and the largest city in Europe. Its population is about 8 million.
London is divided into several parts: the City, Westminster, the West End, and the East End.
The heart of London is the City, its financial and business centre. Numerous banks, offices, and firms are situated there, including the Bank of England, the Stock Exchange, and the Old Bailey. Few people live here, but over a million people come to the City to work. There are some famous ancient buildings within the City. Perhaps the most striking of them is the St. Paul's Cathedral, the greatest of English churches. It was built in the 17th century by Sir Christopher Wren. The Tower of London was founded by Julius Caesar and in 1066 rebuilt by William the Conqueror. It was used as a fortress, a royal palace, and a prison. Now it is a museum.
Westminster is the governmental part of London.
Nearly all English kings and queens have been crowned in Westminster Abbey. Many outstanding statesmen, scientists, writers, poets, and painters are buried here: Newton, Darwin, Chaucer, Dickens, Tennyson, Kipling, etc.
Across the road from Westminster Abbey is Westminster Palace, the seat of the British Parliament. The Clock Tower of the Houses of Parliament is famous for its big bell, known as "Big Ben". Buckingham Palace is the official residence of the Queen.
The West End is the richest and most beautiful part of London. It is the symbol of wealth and luxury. The best hotels, shops, restaurants, clubs, and theatres are situated there.
The Trafalgar Square is the geographical centre of London. It was named in memory of Admiral Nelson's victory in the battle of Trafalgar in 1805. The tall Nelson's Column stands in the middle of the square.
On the north side of the Trafalgar Square is the National Portrait Gallery. Not far away is the British Museum — the biggest museum in London. It contains a priceless collection of ancient manuscripts, coins, sculptures, etc, and is also famous for its library.
There are a lot of factories, workshops, and docks in the East End.

**Comment by dmitrykrivaltsevich** [comment]
@AntonZarutsky , could you please merge it?

**Comment by brntbeer** [comment]
@AntonZarutsky ...feel free to merge this. lol

**Pull request merged**
